#!/bin/bash

hadCases=0

if [ $# -ne 1 ]; then
  echo "WOPWOP requires one argument: the full path to the namelist file."
  exit
fi

# Make sure the namelist exists
if [ -s "$1" ] && [ -r "$1" ]; then
  
  # Move the old cases.nam out of the way, but save it
  if [ -e "cases.nam" ]; then
    hadCases=1
    mv "cases.nam" "cases.nam.autobak"
  fi

  # Seperate the variables
  dir=`dirname "$1"`
  nam=`basename "$1"`

  # Write the cases.nam file
  echo "! Autogenerated by run_wopwop3.sh" > cases.nam
  echo >> cases.nam
  echo "&caseName" >> cases.nam
  echo "  globalFolderName='"$dir"/'" >> cases.nam

  echo "  caseNameFile='"$nam"'" >> cases.nam
  echo "/" >> cases.nam

  # Call WOPWOP
  ./wopwop3

  # Put the old cases file back
#if [ $hadCases -eq 1 ]; then
#   rm -f cases.nam
#mv cases.nam.autobak cases.nam
# fi
  
else
  echo "Cannot open the file $1"
fi
