# clean up 
rm -rf wopwop.err
rm -rf wopwop.out
rm -rf OUTPUT.txt

#Make sure the code is compiled 
make lionxm  
# code from run_wopwop.sh for specifying case
hadCases=0
if [ $# -ne 1 ]; then
  # if cases.nam exists we use that one, otherwise
  #make the new one with the specified path
  if [ -e "cases.nam" ]; then
    hadCases=1
  else
    echo " No cases.nam found."
    echo " This script requires one argument to create cases.nam:"
    echo " the full path to the namelist file."
    exit
  fi
fi

if [ $hadCases -ne 1 ]; then

  # Seperate the variables
  dir=`dirname "$1"`
  nam=`basename "$1"`

  # Write the cases.nam file
  echo "! Autogenerated by runlionxm.sh" > cases.nam
  echo >> cases.nam
  echo "&caseName" >> cases.nam
  echo "  globalFolderName='"$dir"/'" >> cases.nam

  echo "  caseNameFile='"$nam"'" >> cases.nam
  echo "/" >> cases.nam
fi

# uncomment the following if debugging in parallel
# Check for any old cases  

jobids=`qstat -u $USER | grep PSU_WOPWOP | awk -F "." '{ print $1}' `
if [ -n "$jobids" ]; then
  echo 'Currently you have the following PSU_WOPWOP jobs on the cluster'
  qstat -u $USER | grep PSU_WOPWOP |
  echo 'Clear old PSU_WOPWOP jobs from queque (y/n)?'
  read ans
  if [ $ans == 'y' ]; then
    for id in $jobids
    do
      echo 'Deleting job, ' $id
      qdel $id
    done
  fi
fi
# end comment out section.
#Submit the current case
 currentjob=`qsub Qlionxm.sh | awk -F "." '{ print $1 }'`
 echo 'Current job is ' $currentjob
 jobrunning=$currentjob
#open a window up to track the code progress
xterm -e tail -F $PWD/OUTPUT.txt
# sleep for awhile (5 min ? ) then check to see if the case is still running
  while [ -n "$jobrunning" ]; do
    sleep 300
#Now we check to see if previous cases has finished or bombed
    jobrunning=`qstat | grep "$currentjob" | awk -F "." '{ print $1 }'`
    if [ -e wopwop.err ]; then
      echo 'Deleted job' $currentjob 'after error' | mail -s jobstatus $USER@psu.edu
      qdel $currentjob
      exit
    fi
  done
 if [ -n wopwop.err ]; then 
  echo 'Job' $currentjob 'completed with no errors' | mail -s jobstatus $USER@psu.edu
 fi
